# Generated by Django 5.2.17 on 2026-09-28 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_at', models.DateTimeField()),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_status', models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late')], max_length=10)),
                ('check_out_status', models.CharField(blank=True, choices=[('normal', 'Normal'), ('early_departure', 'Early'), ('missed_checkout', 'Missed')], max_length=20)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('activity_report_status', models.CharField(default='pending', max_length=12)),
                ('review_status', models.CharField(choices=[('normal', 'Normal'), ('review_required', 'Review')], default='normal', max_length=16)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('remarks', models.TextField(blank=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org.campus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=3)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy_m', models.FloatField()),
                ('inside_geofence', models.BooleanField()),
                ('distance_m', models.FloatField(null=True)),
                ('auth_method', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('recorded_at', models.DateTimeField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org.campus')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.registereddevice')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='attendance.attendancerecord')),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(default='completed', max_length=20)),
                ('output', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.activitycategory')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='attendance.attendancerecord')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='activity_docs/%Y/%m/')),
                ('original_name', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='attendance.dailyactivity')),
            ],
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date', 'campus'], name='attendance__date_22af9a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['user', '-date'], name='attendance__user_id_e2bd98_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='uniq_attendance_per_user_day'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('check_out_at__isnull', True), ('check_out_at__gte', models.F('check_in_at')), _connector='OR'), name='checkout_after_checkin'),
        ),
    ]
