# Generated by Codex on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("attendance", "0002_holiday_attendancecorrection_leaverecord_and_more")]

    operations = [
        migrations.AlterField(
            model_name="leaverecord",
            name="kind",
            field=models.CharField(choices=[
                ("annual", "Annual"), ("sick", "Sick"), ("training", "Training"),
                ("study", "Study"), ("conference", "Conference"), ("official_travel", "Travel"),
                ("permission", "Permission"), ("other", "Other"),
            ], max_length=20),
        ),
    ]
