# Generated by Django 5.2.17 on 2026-10-03 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendancerecord_check_out_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecord',
            name='recall_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='recalled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='recalled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_recalls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officialduty',
            name='recall_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialduty',
            name='recalled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialduty',
            name='recalled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_recalls', to=settings.AUTH_USER_MODEL),
        ),
    ]
