# Generated by Django 5.2.17 on 2026-10-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_leaverecord_recall_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecord',
            name='recall_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='officialduty',
            name='recall_reason',
            field=models.TextField(blank=True),
        ),
    ]
