# Generated by Django 5.2.17 on 2026-10-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_leaverecord_recall_reason_officialduty_recall_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('recalled', 'Recalled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='officialduty',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('recalled', 'Recalled')], default='pending', max_length=10),
        ),
    ]
