# Generated by Django 5.2.17 on 2026-09-29 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_remove_user_division_and_more'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Division',
        ),
    ]
